using System.Buffers.Binary;

namespace CM26.AssetBridge;

internal static class FrostbiteTextureExporter
{
    public const uint TextureResType = 0x6BDE20BA;

    // Values come from the FC26 RenderFormat enum generated by the installed FMT SDK.
    // These are every format currently present in the desktop FC26 asset catalog and
    // every one has a direct DXGI representation in a DDS DX10 header.
    public static bool SupportsRenderFormat(int renderFormat) =>
        renderFormat is 6 or 18 or 20 or 27 or 29 or 31 or 36 or 40 or 41 or 51
            or >= 54 and <= 67;

    public static string ExportDds(
        string gameRoot,
        IReadOnlyDictionary<uint, string> catalogs,
        FrostbiteIndexedAsset resource)
    {
        if (resource.Kind != FrostbiteAssetKind.Res || resource.ResType != TextureResType)
            throw new InvalidDataException("Selected RES entry is not a Frostbite texture.");

        var header = FrostbitePayloadReader.ReadDecoded(gameRoot, catalogs, resource);
        if (header.Length < 168)
            throw new InvalidDataException("FC26 texture header is truncated.");

        var pixelFormat = BinaryPrimitives.ReadInt32LittleEndian(header.AsSpan(12, 4));
        var width = BinaryPrimitives.ReadUInt16LittleEndian(header.AsSpan(22, 2));
        var height = BinaryPrimitives.ReadUInt16LittleEndian(header.AsSpan(24, 2));
        var mipCount = header[30];
        var chunkId = new Guid(header.AsSpan(40, 16));
        var chunk = FrostbiteAssetIndexStore.FindExact(
            chunkId.ToString("D"), FrostbiteAssetKind.Chunk)
            ?? throw new FileNotFoundException($"Texture chunk was not indexed: {chunkId}");
        var pixels = FrostbitePayloadReader.ReadDecoded(gameRoot, catalogs, chunk);

        var ddsHeader = CreateDdsHeader(pixelFormat, width, height, mipCount, pixels.Length);
        var root = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "Creation Master 26", "extracted-assets");
        Directory.CreateDirectory(root);
        var destination = Path.Combine(root, resource.Sha1 + ".dds");
        var temporary = destination + ".tmp";
        using (var stream = new FileStream(temporary, FileMode.Create, FileAccess.Write, FileShare.None))
        {
            stream.Write(ddsHeader);
            stream.Write(pixels);
            stream.Flush(flushToDisk: true);
        }
        File.Move(temporary, destination, overwrite: true);
        return destination;
    }

    private static byte[] CreateDdsHeader(
        int renderFormat, int width, int height, int mipCount, int dataLength)
    {
        var dxgiFormat = renderFormat switch
        {
            6 => 61u,   // R8_UNORM
            18 => 28u,  // R8G8B8A8_UNORM
            20 => 29u,  // R8G8B8A8_UNORM_SRGB
            27 => 24u,  // R10G10B10A2_UNORM
            29 => 67u,  // R9G9B9E5_SHAREDEXP
            31 => 56u,  // R16_UNORM
            36 => 35u,  // R16G16_UNORM
            40 => 10u,  // R16G16B16A16_FLOAT
            41 => 11u,  // R16G16B16A16_UNORM
            51 => 2u,   // R32G32B32A32_FLOAT
            54 or 56 => 71u, // BC1_UNORM / BC1A_UNORM
            55 or 57 => 72u, // BC1_SRGB / BC1A_SRGB
            58 => 74u,  // BC2_UNORM
            59 => 75u,  // BC2_SRGB
            60 => 77u,  // BC3_UNORM
            61 => 78u,  // BC3_SRGB
            62 => 80u,  // BC4_UNORM
            63 => 83u,  // BC5_UNORM
            64 => 95u,  // BC6H_UF16
            65 => 96u,  // BC6H_SF16
            66 => 98u,  // BC7_UNORM
            67 => 99u,  // BC7_UNORM_SRGB
            _ => throw new NotSupportedException(
                $"FC26 texture RenderFormat {renderFormat} is not supported by the DDS exporter."),
        };

        var header = new byte[148];
        WriteUInt32(header, 0, 0x20534444); // "DDS "
        WriteUInt32(header, 4, 124);
        const uint caps = 0x1;
        const uint heightFlag = 0x2;
        const uint widthFlag = 0x4;
        const uint pixelFormatFlag = 0x1000;
        const uint pitchFlag = 0x8;
        const uint linearSizeFlag = 0x80000;
        const uint mipMapCountFlag = 0x20000;
        var compressed = renderFormat is >= 54 and <= 67;
        var flags = caps | heightFlag | widthFlag | pixelFormatFlag |
            (compressed ? linearSizeFlag : pitchFlag);
        if (mipCount > 1) flags |= mipMapCountFlag;
        WriteUInt32(header, 8, flags);
        WriteUInt32(header, 12, checked((uint)height));
        WriteUInt32(header, 16, checked((uint)width));
        WriteUInt32(header, 20, compressed
            ? checked((uint)TopMipSize(renderFormat, width, height))
            : checked((uint)RowPitch(renderFormat, width)));
        WriteUInt32(header, 28, checked((uint)Math.Max(1, mipCount)));

        WriteUInt32(header, 76, 32);       // DDS_PIXELFORMAT size
        WriteUInt32(header, 80, 0x4);      // DDPF_FOURCC
        WriteUInt32(header, 84, 0x30315844); // "DX10"

        var textureCaps = 0x1000u;         // DDSCAPS_TEXTURE
        if (mipCount > 1) textureCaps |= 0x8u | 0x400000u;
        WriteUInt32(header, 108, textureCaps);
        WriteUInt32(header, 128, dxgiFormat);
        WriteUInt32(header, 132, 3); // D3D10_RESOURCE_DIMENSION_TEXTURE2D
        WriteUInt32(header, 136, 0); // misc flag
        WriteUInt32(header, 140, 1); // array size
        WriteUInt32(header, 144, 0); // misc flags 2
        return header;
    }

    private static int TopMipSize(int renderFormat, int width, int height)
    {
        var bytesPerBlock = renderFormat is 54 or 55 or 56 or 57 or 62 ? 8 : 16;
        return checked(Math.Max(1, (width + 3) / 4) * Math.Max(1, (height + 3) / 4) * bytesPerBlock);
    }

    private static int RowPitch(int renderFormat, int width)
    {
        var bitsPerPixel = renderFormat switch
        {
            6 => 8,
            18 or 20 or 27 or 29 or 36 => 32,
            31 => 16,
            40 or 41 => 64,
            51 => 128,
            _ => throw new NotSupportedException($"No row-pitch mapping for RenderFormat {renderFormat}."),
        };
        return checked((width * bitsPerPixel + 7) / 8);
    }

    private static void WriteUInt32(byte[] data, int offset, uint value) =>
        BinaryPrimitives.WriteUInt32LittleEndian(data.AsSpan(offset, 4), value);
}
