using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace FifaControls;

public class WeatherForm : Form
{
	private IContainer components;

	private Label label1;

	private Label label2;

	private Label label3;

	private Label label4;

	private Label label5;

	private Label label6;

	private Label label7;

	private Label label8;

	private NumericUpDown numericJanOvercast;

	private DomainUpDown domainJanSunset;

	private DomainUpDown domainJanDark;

	private NumericUpDown numericJanRain;

	private NumericUpDown numericJanSnow;

	private NumericUpDown numericUpDown1;

	private NumericUpDown numericUpDown2;

	private DomainUpDown domainUpDown1;

	private DomainUpDown domainUpDown2;

	private NumericUpDown numericFebOvercast;

	private Label label9;

	private NumericUpDown numericUpDown3;

	private NumericUpDown numericUpDown4;

	private DomainUpDown domainUpDown3;

	private DomainUpDown domainUpDown4;

	private NumericUpDown numericUpDown5;

	private Label label10;

	private NumericUpDown numericUpDown6;

	private NumericUpDown numericUpDown7;

	private DomainUpDown domainUpDown5;

	private DomainUpDown domainUpDown6;

	private NumericUpDown numericUpDown8;

	private Label label11;

	private NumericUpDown numericUpDown9;

	private NumericUpDown numericUpDown10;

	private DomainUpDown domainUpDown7;

	private DomainUpDown domainUpDown8;

	private NumericUpDown numericUpDown11;

	private Label label12;

	private NumericUpDown numericUpDown12;

	private NumericUpDown numericUpDown13;

	private DomainUpDown domainUpDown9;

	private DomainUpDown domainUpDown10;

	private NumericUpDown numericUpDown14;

	private Label label13;

	private NumericUpDown numericUpDown15;

	private NumericUpDown numericUpDown16;

	private DomainUpDown domainUpDown11;

	private DomainUpDown domainUpDown12;

	private NumericUpDown numericUpDown17;

	private Label label14;

	private NumericUpDown numericUpDown18;

	private NumericUpDown numericUpDown19;

	private DomainUpDown domainUpDown13;

	private DomainUpDown domainUpDown14;

	private NumericUpDown numericUpDown20;

	private Label label15;

	private NumericUpDown numericUpDown21;

	private NumericUpDown numericUpDown22;

	private DomainUpDown domainUpDown15;

	private DomainUpDown domainUpDown16;

	private NumericUpDown numericUpDown23;

	private Label label16;

	private NumericUpDown numericUpDown24;

	private NumericUpDown numericUpDown25;

	private DomainUpDown domainUpDown17;

	private DomainUpDown domainUpDown18;

	private NumericUpDown numericUpDown26;

	private Label label17;

	private NumericUpDown numericUpDown27;

	private NumericUpDown numericUpDown28;

	private DomainUpDown domainUpDown19;

	private DomainUpDown domainUpDown20;

	private NumericUpDown numericUpDown29;

	private Label label18;

	private NumericUpDown numericUpDown30;

	private NumericUpDown numericUpDown31;

	private DomainUpDown domainUpDown21;

	private DomainUpDown domainUpDown22;

	private NumericUpDown numericUpDown32;

	private Label label19;

	private Button buttonOk;

	private Button buttonCancel;

	public WeatherForm()
	{
		InitializeComponent();
	}

	protected override void Dispose(bool disposing)
	{
		if (disposing && components != null)
		{
			components.Dispose();
		}
		base.Dispose(disposing);
	}

	private void InitializeComponent()
	{
		System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FifaControls.WeatherForm));
		this.label1 = new System.Windows.Forms.Label();
		this.label2 = new System.Windows.Forms.Label();
		this.label3 = new System.Windows.Forms.Label();
		this.label4 = new System.Windows.Forms.Label();
		this.label5 = new System.Windows.Forms.Label();
		this.label6 = new System.Windows.Forms.Label();
		this.label7 = new System.Windows.Forms.Label();
		this.label8 = new System.Windows.Forms.Label();
		this.numericJanOvercast = new System.Windows.Forms.NumericUpDown();
		this.domainJanSunset = new System.Windows.Forms.DomainUpDown();
		this.domainJanDark = new System.Windows.Forms.DomainUpDown();
		this.numericJanRain = new System.Windows.Forms.NumericUpDown();
		this.numericJanSnow = new System.Windows.Forms.NumericUpDown();
		this.numericUpDown1 = new System.Windows.Forms.NumericUpDown();
		this.numericUpDown2 = new System.Windows.Forms.NumericUpDown();
		this.domainUpDown1 = new System.Windows.Forms.DomainUpDown();
		this.domainUpDown2 = new System.Windows.Forms.DomainUpDown();
		this.numericFebOvercast = new System.Windows.Forms.NumericUpDown();
		this.label9 = new System.Windows.Forms.Label();
		this.numericUpDown3 = new System.Windows.Forms.NumericUpDown();
		this.numericUpDown4 = new System.Windows.Forms.NumericUpDown();
		this.domainUpDown3 = new System.Windows.Forms.DomainUpDown();
		this.domainUpDown4 = new System.Windows.Forms.DomainUpDown();
		this.numericUpDown5 = new System.Windows.Forms.NumericUpDown();
		this.label10 = new System.Windows.Forms.Label();
		this.numericUpDown6 = new System.Windows.Forms.NumericUpDown();
		this.numericUpDown7 = new System.Windows.Forms.NumericUpDown();
		this.domainUpDown5 = new System.Windows.Forms.DomainUpDown();
		this.domainUpDown6 = new System.Windows.Forms.DomainUpDown();
		this.numericUpDown8 = new System.Windows.Forms.NumericUpDown();
		this.label11 = new System.Windows.Forms.Label();
		this.numericUpDown9 = new System.Windows.Forms.NumericUpDown();
		this.numericUpDown10 = new System.Windows.Forms.NumericUpDown();
		this.domainUpDown7 = new System.Windows.Forms.DomainUpDown();
		this.domainUpDown8 = new System.Windows.Forms.DomainUpDown();
		this.numericUpDown11 = new System.Windows.Forms.NumericUpDown();
		this.label12 = new System.Windows.Forms.Label();
		this.numericUpDown12 = new System.Windows.Forms.NumericUpDown();
		this.numericUpDown13 = new System.Windows.Forms.NumericUpDown();
		this.domainUpDown9 = new System.Windows.Forms.DomainUpDown();
		this.domainUpDown10 = new System.Windows.Forms.DomainUpDown();
		this.numericUpDown14 = new System.Windows.Forms.NumericUpDown();
		this.label13 = new System.Windows.Forms.Label();
		this.numericUpDown15 = new System.Windows.Forms.NumericUpDown();
		this.numericUpDown16 = new System.Windows.Forms.NumericUpDown();
		this.domainUpDown11 = new System.Windows.Forms.DomainUpDown();
		this.domainUpDown12 = new System.Windows.Forms.DomainUpDown();
		this.numericUpDown17 = new System.Windows.Forms.NumericUpDown();
		this.label14 = new System.Windows.Forms.Label();
		this.numericUpDown18 = new System.Windows.Forms.NumericUpDown();
		this.numericUpDown19 = new System.Windows.Forms.NumericUpDown();
		this.domainUpDown13 = new System.Windows.Forms.DomainUpDown();
		this.domainUpDown14 = new System.Windows.Forms.DomainUpDown();
		this.numericUpDown20 = new System.Windows.Forms.NumericUpDown();
		this.label15 = new System.Windows.Forms.Label();
		this.numericUpDown21 = new System.Windows.Forms.NumericUpDown();
		this.numericUpDown22 = new System.Windows.Forms.NumericUpDown();
		this.domainUpDown15 = new System.Windows.Forms.DomainUpDown();
		this.domainUpDown16 = new System.Windows.Forms.DomainUpDown();
		this.numericUpDown23 = new System.Windows.Forms.NumericUpDown();
		this.label16 = new System.Windows.Forms.Label();
		this.numericUpDown24 = new System.Windows.Forms.NumericUpDown();
		this.numericUpDown25 = new System.Windows.Forms.NumericUpDown();
		this.domainUpDown17 = new System.Windows.Forms.DomainUpDown();
		this.domainUpDown18 = new System.Windows.Forms.DomainUpDown();
		this.numericUpDown26 = new System.Windows.Forms.NumericUpDown();
		this.label17 = new System.Windows.Forms.Label();
		this.numericUpDown27 = new System.Windows.Forms.NumericUpDown();
		this.numericUpDown28 = new System.Windows.Forms.NumericUpDown();
		this.domainUpDown19 = new System.Windows.Forms.DomainUpDown();
		this.domainUpDown20 = new System.Windows.Forms.DomainUpDown();
		this.numericUpDown29 = new System.Windows.Forms.NumericUpDown();
		this.label18 = new System.Windows.Forms.Label();
		this.numericUpDown30 = new System.Windows.Forms.NumericUpDown();
		this.numericUpDown31 = new System.Windows.Forms.NumericUpDown();
		this.domainUpDown21 = new System.Windows.Forms.DomainUpDown();
		this.domainUpDown22 = new System.Windows.Forms.DomainUpDown();
		this.numericUpDown32 = new System.Windows.Forms.NumericUpDown();
		this.label19 = new System.Windows.Forms.Label();
		this.buttonOk = new System.Windows.Forms.Button();
		this.buttonCancel = new System.Windows.Forms.Button();
		((System.ComponentModel.ISupportInitialize)this.numericJanOvercast).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericJanRain).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericJanSnow).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown1).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown2).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericFebOvercast).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown3).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown4).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown5).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown6).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown7).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown8).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown9).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown10).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown11).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown12).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown13).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown14).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown15).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown16).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown17).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown18).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown19).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown20).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown21).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown22).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown23).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown24).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown25).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown26).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown27).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown28).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown29).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown30).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown31).BeginInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown32).BeginInit();
		base.SuspendLayout();
		this.label1.AutoSize = true;
		this.label1.Location = new System.Drawing.Point(19, 66);
		this.label1.Name = "label1";
		this.label1.Size = new System.Drawing.Size(27, 13);
		this.label1.TabIndex = 0;
		this.label1.Text = "JAN";
		this.label2.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
		this.label2.Location = new System.Drawing.Point(55, 9);
		this.label2.Name = "label2";
		this.label2.Size = new System.Drawing.Size(248, 23);
		this.label2.TabIndex = 1;
		this.label2.Text = "Probability";
		this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
		this.label3.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
		this.label3.Location = new System.Drawing.Point(55, 34);
		this.label3.Name = "label3";
		this.label3.Size = new System.Drawing.Size(79, 23);
		this.label3.TabIndex = 2;
		this.label3.Text = "Overcast";
		this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
		this.label4.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
		this.label4.Location = new System.Drawing.Point(139, 34);
		this.label4.Name = "label4";
		this.label4.Size = new System.Drawing.Size(79, 23);
		this.label4.TabIndex = 3;
		this.label4.Text = "Rain";
		this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
		this.label5.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
		this.label5.Location = new System.Drawing.Point(224, 34);
		this.label5.Name = "label5";
		this.label5.Size = new System.Drawing.Size(79, 23);
		this.label5.TabIndex = 4;
		this.label5.Text = "Snow";
		this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
		this.label6.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
		this.label6.Location = new System.Drawing.Point(309, 9);
		this.label6.Name = "label6";
		this.label6.Size = new System.Drawing.Size(163, 23);
		this.label6.TabIndex = 5;
		this.label6.Text = "Time";
		this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
		this.label7.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
		this.label7.Location = new System.Drawing.Point(393, 34);
		this.label7.Name = "label7";
		this.label7.Size = new System.Drawing.Size(79, 23);
		this.label7.TabIndex = 7;
		this.label7.Text = "Totall Dark";
		this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
		this.label8.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
		this.label8.Location = new System.Drawing.Point(309, 34);
		this.label8.Name = "label8";
		this.label8.Size = new System.Drawing.Size(79, 23);
		this.label8.TabIndex = 6;
		this.label8.Text = "Sunset";
		this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
		this.numericJanOvercast.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericJanOvercast.Location = new System.Drawing.Point(55, 64);
		this.numericJanOvercast.Name = "numericJanOvercast";
		this.numericJanOvercast.Size = new System.Drawing.Size(79, 20);
		this.numericJanOvercast.TabIndex = 8;
		this.numericJanOvercast.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.domainJanSunset.Items.Add("16.00");
		this.domainJanSunset.Items.Add("16.30");
		this.domainJanSunset.Items.Add("17.00");
		this.domainJanSunset.Items.Add("17.30");
		this.domainJanSunset.Items.Add("18.00");
		this.domainJanSunset.Items.Add("18.30");
		this.domainJanSunset.Items.Add("19.00");
		this.domainJanSunset.Items.Add("19.30");
		this.domainJanSunset.Items.Add("20.00");
		this.domainJanSunset.Location = new System.Drawing.Point(309, 64);
		this.domainJanSunset.Name = "domainJanSunset";
		this.domainJanSunset.Size = new System.Drawing.Size(79, 20);
		this.domainJanSunset.TabIndex = 9;
		this.domainJanDark.Items.Add("17.00");
		this.domainJanDark.Items.Add("17.30");
		this.domainJanDark.Items.Add("18.00");
		this.domainJanDark.Items.Add("18.30");
		this.domainJanDark.Items.Add("19.00");
		this.domainJanDark.Items.Add("19.30");
		this.domainJanDark.Items.Add("20.00");
		this.domainJanDark.Items.Add("20.30");
		this.domainJanDark.Items.Add("21.00");
		this.domainJanDark.Items.Add("21.30");
		this.domainJanDark.Items.Add("22.00");
		this.domainJanDark.Items.Add("22.30");
		this.domainJanDark.Location = new System.Drawing.Point(393, 64);
		this.domainJanDark.Name = "domainJanDark";
		this.domainJanDark.Size = new System.Drawing.Size(79, 20);
		this.domainJanDark.TabIndex = 10;
		this.numericJanRain.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericJanRain.Location = new System.Drawing.Point(139, 64);
		this.numericJanRain.Name = "numericJanRain";
		this.numericJanRain.Size = new System.Drawing.Size(79, 20);
		this.numericJanRain.TabIndex = 11;
		this.numericJanRain.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericJanSnow.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericJanSnow.Location = new System.Drawing.Point(224, 64);
		this.numericJanSnow.Name = "numericJanSnow";
		this.numericJanSnow.Size = new System.Drawing.Size(79, 20);
		this.numericJanSnow.TabIndex = 12;
		this.numericJanSnow.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericUpDown1.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown1.Location = new System.Drawing.Point(224, 91);
		this.numericUpDown1.Name = "numericUpDown1";
		this.numericUpDown1.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown1.TabIndex = 18;
		this.numericUpDown1.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericUpDown2.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown2.Location = new System.Drawing.Point(139, 91);
		this.numericUpDown2.Name = "numericUpDown2";
		this.numericUpDown2.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown2.TabIndex = 17;
		this.numericUpDown2.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.domainUpDown1.Items.Add("17.00");
		this.domainUpDown1.Items.Add("17.30");
		this.domainUpDown1.Items.Add("18.00");
		this.domainUpDown1.Items.Add("18.30");
		this.domainUpDown1.Items.Add("19.00");
		this.domainUpDown1.Items.Add("19.30");
		this.domainUpDown1.Items.Add("20.00");
		this.domainUpDown1.Items.Add("20.30");
		this.domainUpDown1.Items.Add("21.00");
		this.domainUpDown1.Items.Add("21.30");
		this.domainUpDown1.Items.Add("22.00");
		this.domainUpDown1.Items.Add("22.30");
		this.domainUpDown1.Location = new System.Drawing.Point(393, 91);
		this.domainUpDown1.Name = "domainUpDown1";
		this.domainUpDown1.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown1.TabIndex = 16;
		this.domainUpDown2.Items.Add("16.00");
		this.domainUpDown2.Items.Add("16.30");
		this.domainUpDown2.Items.Add("17.00");
		this.domainUpDown2.Items.Add("17.30");
		this.domainUpDown2.Items.Add("18.00");
		this.domainUpDown2.Items.Add("18.30");
		this.domainUpDown2.Items.Add("19.00");
		this.domainUpDown2.Items.Add("19.30");
		this.domainUpDown2.Items.Add("20.00");
		this.domainUpDown2.Location = new System.Drawing.Point(309, 91);
		this.domainUpDown2.Name = "domainUpDown2";
		this.domainUpDown2.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown2.TabIndex = 15;
		this.numericFebOvercast.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericFebOvercast.Location = new System.Drawing.Point(55, 91);
		this.numericFebOvercast.Name = "numericFebOvercast";
		this.numericFebOvercast.Size = new System.Drawing.Size(79, 20);
		this.numericFebOvercast.TabIndex = 14;
		this.numericFebOvercast.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.label9.AutoSize = true;
		this.label9.Location = new System.Drawing.Point(19, 93);
		this.label9.Name = "label9";
		this.label9.Size = new System.Drawing.Size(27, 13);
		this.label9.TabIndex = 13;
		this.label9.Text = "FEB";
		this.numericUpDown3.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown3.Location = new System.Drawing.Point(224, 117);
		this.numericUpDown3.Name = "numericUpDown3";
		this.numericUpDown3.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown3.TabIndex = 24;
		this.numericUpDown3.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericUpDown4.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown4.Location = new System.Drawing.Point(139, 117);
		this.numericUpDown4.Name = "numericUpDown4";
		this.numericUpDown4.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown4.TabIndex = 23;
		this.numericUpDown4.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.domainUpDown3.Items.Add("17.00");
		this.domainUpDown3.Items.Add("17.30");
		this.domainUpDown3.Items.Add("18.00");
		this.domainUpDown3.Items.Add("18.30");
		this.domainUpDown3.Items.Add("19.00");
		this.domainUpDown3.Items.Add("19.30");
		this.domainUpDown3.Items.Add("20.00");
		this.domainUpDown3.Items.Add("20.30");
		this.domainUpDown3.Items.Add("21.00");
		this.domainUpDown3.Items.Add("21.30");
		this.domainUpDown3.Items.Add("22.00");
		this.domainUpDown3.Items.Add("22.30");
		this.domainUpDown3.Location = new System.Drawing.Point(393, 117);
		this.domainUpDown3.Name = "domainUpDown3";
		this.domainUpDown3.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown3.TabIndex = 22;
		this.domainUpDown4.Items.Add("16.00");
		this.domainUpDown4.Items.Add("16.30");
		this.domainUpDown4.Items.Add("17.00");
		this.domainUpDown4.Items.Add("17.30");
		this.domainUpDown4.Items.Add("18.00");
		this.domainUpDown4.Items.Add("18.30");
		this.domainUpDown4.Items.Add("19.00");
		this.domainUpDown4.Items.Add("19.30");
		this.domainUpDown4.Items.Add("20.00");
		this.domainUpDown4.Location = new System.Drawing.Point(309, 117);
		this.domainUpDown4.Name = "domainUpDown4";
		this.domainUpDown4.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown4.TabIndex = 21;
		this.numericUpDown5.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown5.Location = new System.Drawing.Point(55, 117);
		this.numericUpDown5.Name = "numericUpDown5";
		this.numericUpDown5.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown5.TabIndex = 20;
		this.numericUpDown5.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.label10.AutoSize = true;
		this.label10.Location = new System.Drawing.Point(19, 119);
		this.label10.Name = "label10";
		this.label10.Size = new System.Drawing.Size(27, 13);
		this.label10.TabIndex = 19;
		this.label10.Text = "FEB";
		this.numericUpDown6.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown6.Location = new System.Drawing.Point(224, 143);
		this.numericUpDown6.Name = "numericUpDown6";
		this.numericUpDown6.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown6.TabIndex = 30;
		this.numericUpDown6.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericUpDown7.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown7.Location = new System.Drawing.Point(139, 143);
		this.numericUpDown7.Name = "numericUpDown7";
		this.numericUpDown7.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown7.TabIndex = 29;
		this.numericUpDown7.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.domainUpDown5.Items.Add("17.00");
		this.domainUpDown5.Items.Add("17.30");
		this.domainUpDown5.Items.Add("18.00");
		this.domainUpDown5.Items.Add("18.30");
		this.domainUpDown5.Items.Add("19.00");
		this.domainUpDown5.Items.Add("19.30");
		this.domainUpDown5.Items.Add("20.00");
		this.domainUpDown5.Items.Add("20.30");
		this.domainUpDown5.Items.Add("21.00");
		this.domainUpDown5.Items.Add("21.30");
		this.domainUpDown5.Items.Add("22.00");
		this.domainUpDown5.Items.Add("22.30");
		this.domainUpDown5.Location = new System.Drawing.Point(393, 143);
		this.domainUpDown5.Name = "domainUpDown5";
		this.domainUpDown5.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown5.TabIndex = 28;
		this.domainUpDown6.Items.Add("16.00");
		this.domainUpDown6.Items.Add("16.30");
		this.domainUpDown6.Items.Add("17.00");
		this.domainUpDown6.Items.Add("17.30");
		this.domainUpDown6.Items.Add("18.00");
		this.domainUpDown6.Items.Add("18.30");
		this.domainUpDown6.Items.Add("19.00");
		this.domainUpDown6.Items.Add("19.30");
		this.domainUpDown6.Items.Add("20.00");
		this.domainUpDown6.Location = new System.Drawing.Point(309, 143);
		this.domainUpDown6.Name = "domainUpDown6";
		this.domainUpDown6.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown6.TabIndex = 27;
		this.numericUpDown8.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown8.Location = new System.Drawing.Point(55, 143);
		this.numericUpDown8.Name = "numericUpDown8";
		this.numericUpDown8.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown8.TabIndex = 26;
		this.numericUpDown8.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.label11.AutoSize = true;
		this.label11.Location = new System.Drawing.Point(19, 145);
		this.label11.Name = "label11";
		this.label11.Size = new System.Drawing.Size(27, 13);
		this.label11.TabIndex = 25;
		this.label11.Text = "FEB";
		this.numericUpDown9.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown9.Location = new System.Drawing.Point(224, 169);
		this.numericUpDown9.Name = "numericUpDown9";
		this.numericUpDown9.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown9.TabIndex = 36;
		this.numericUpDown9.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericUpDown10.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown10.Location = new System.Drawing.Point(139, 169);
		this.numericUpDown10.Name = "numericUpDown10";
		this.numericUpDown10.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown10.TabIndex = 35;
		this.numericUpDown10.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.domainUpDown7.Items.Add("17.00");
		this.domainUpDown7.Items.Add("17.30");
		this.domainUpDown7.Items.Add("18.00");
		this.domainUpDown7.Items.Add("18.30");
		this.domainUpDown7.Items.Add("19.00");
		this.domainUpDown7.Items.Add("19.30");
		this.domainUpDown7.Items.Add("20.00");
		this.domainUpDown7.Items.Add("20.30");
		this.domainUpDown7.Items.Add("21.00");
		this.domainUpDown7.Items.Add("21.30");
		this.domainUpDown7.Items.Add("22.00");
		this.domainUpDown7.Items.Add("22.30");
		this.domainUpDown7.Location = new System.Drawing.Point(393, 169);
		this.domainUpDown7.Name = "domainUpDown7";
		this.domainUpDown7.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown7.TabIndex = 34;
		this.domainUpDown8.Items.Add("16.00");
		this.domainUpDown8.Items.Add("16.30");
		this.domainUpDown8.Items.Add("17.00");
		this.domainUpDown8.Items.Add("17.30");
		this.domainUpDown8.Items.Add("18.00");
		this.domainUpDown8.Items.Add("18.30");
		this.domainUpDown8.Items.Add("19.00");
		this.domainUpDown8.Items.Add("19.30");
		this.domainUpDown8.Items.Add("20.00");
		this.domainUpDown8.Location = new System.Drawing.Point(309, 169);
		this.domainUpDown8.Name = "domainUpDown8";
		this.domainUpDown8.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown8.TabIndex = 33;
		this.numericUpDown11.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown11.Location = new System.Drawing.Point(55, 169);
		this.numericUpDown11.Name = "numericUpDown11";
		this.numericUpDown11.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown11.TabIndex = 32;
		this.numericUpDown11.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.label12.AutoSize = true;
		this.label12.Location = new System.Drawing.Point(19, 171);
		this.label12.Name = "label12";
		this.label12.Size = new System.Drawing.Size(27, 13);
		this.label12.TabIndex = 31;
		this.label12.Text = "FEB";
		this.numericUpDown12.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown12.Location = new System.Drawing.Point(224, 194);
		this.numericUpDown12.Name = "numericUpDown12";
		this.numericUpDown12.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown12.TabIndex = 42;
		this.numericUpDown12.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericUpDown13.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown13.Location = new System.Drawing.Point(139, 194);
		this.numericUpDown13.Name = "numericUpDown13";
		this.numericUpDown13.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown13.TabIndex = 41;
		this.numericUpDown13.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.domainUpDown9.Items.Add("17.00");
		this.domainUpDown9.Items.Add("17.30");
		this.domainUpDown9.Items.Add("18.00");
		this.domainUpDown9.Items.Add("18.30");
		this.domainUpDown9.Items.Add("19.00");
		this.domainUpDown9.Items.Add("19.30");
		this.domainUpDown9.Items.Add("20.00");
		this.domainUpDown9.Items.Add("20.30");
		this.domainUpDown9.Items.Add("21.00");
		this.domainUpDown9.Items.Add("21.30");
		this.domainUpDown9.Items.Add("22.00");
		this.domainUpDown9.Items.Add("22.30");
		this.domainUpDown9.Location = new System.Drawing.Point(393, 194);
		this.domainUpDown9.Name = "domainUpDown9";
		this.domainUpDown9.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown9.TabIndex = 40;
		this.domainUpDown10.Items.Add("16.00");
		this.domainUpDown10.Items.Add("16.30");
		this.domainUpDown10.Items.Add("17.00");
		this.domainUpDown10.Items.Add("17.30");
		this.domainUpDown10.Items.Add("18.00");
		this.domainUpDown10.Items.Add("18.30");
		this.domainUpDown10.Items.Add("19.00");
		this.domainUpDown10.Items.Add("19.30");
		this.domainUpDown10.Items.Add("20.00");
		this.domainUpDown10.Location = new System.Drawing.Point(309, 194);
		this.domainUpDown10.Name = "domainUpDown10";
		this.domainUpDown10.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown10.TabIndex = 39;
		this.numericUpDown14.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown14.Location = new System.Drawing.Point(55, 194);
		this.numericUpDown14.Name = "numericUpDown14";
		this.numericUpDown14.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown14.TabIndex = 38;
		this.numericUpDown14.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.label13.AutoSize = true;
		this.label13.Location = new System.Drawing.Point(19, 196);
		this.label13.Name = "label13";
		this.label13.Size = new System.Drawing.Size(27, 13);
		this.label13.TabIndex = 37;
		this.label13.Text = "FEB";
		this.numericUpDown15.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown15.Location = new System.Drawing.Point(224, 218);
		this.numericUpDown15.Name = "numericUpDown15";
		this.numericUpDown15.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown15.TabIndex = 48;
		this.numericUpDown15.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericUpDown16.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown16.Location = new System.Drawing.Point(139, 218);
		this.numericUpDown16.Name = "numericUpDown16";
		this.numericUpDown16.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown16.TabIndex = 47;
		this.numericUpDown16.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.domainUpDown11.Items.Add("17.00");
		this.domainUpDown11.Items.Add("17.30");
		this.domainUpDown11.Items.Add("18.00");
		this.domainUpDown11.Items.Add("18.30");
		this.domainUpDown11.Items.Add("19.00");
		this.domainUpDown11.Items.Add("19.30");
		this.domainUpDown11.Items.Add("20.00");
		this.domainUpDown11.Items.Add("20.30");
		this.domainUpDown11.Items.Add("21.00");
		this.domainUpDown11.Items.Add("21.30");
		this.domainUpDown11.Items.Add("22.00");
		this.domainUpDown11.Items.Add("22.30");
		this.domainUpDown11.Location = new System.Drawing.Point(393, 218);
		this.domainUpDown11.Name = "domainUpDown11";
		this.domainUpDown11.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown11.TabIndex = 46;
		this.domainUpDown12.Items.Add("16.00");
		this.domainUpDown12.Items.Add("16.30");
		this.domainUpDown12.Items.Add("17.00");
		this.domainUpDown12.Items.Add("17.30");
		this.domainUpDown12.Items.Add("18.00");
		this.domainUpDown12.Items.Add("18.30");
		this.domainUpDown12.Items.Add("19.00");
		this.domainUpDown12.Items.Add("19.30");
		this.domainUpDown12.Items.Add("20.00");
		this.domainUpDown12.Location = new System.Drawing.Point(309, 218);
		this.domainUpDown12.Name = "domainUpDown12";
		this.domainUpDown12.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown12.TabIndex = 45;
		this.numericUpDown17.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown17.Location = new System.Drawing.Point(55, 218);
		this.numericUpDown17.Name = "numericUpDown17";
		this.numericUpDown17.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown17.TabIndex = 44;
		this.numericUpDown17.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.label14.AutoSize = true;
		this.label14.Location = new System.Drawing.Point(19, 220);
		this.label14.Name = "label14";
		this.label14.Size = new System.Drawing.Size(27, 13);
		this.label14.TabIndex = 43;
		this.label14.Text = "FEB";
		this.numericUpDown18.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown18.Location = new System.Drawing.Point(224, 243);
		this.numericUpDown18.Name = "numericUpDown18";
		this.numericUpDown18.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown18.TabIndex = 54;
		this.numericUpDown18.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericUpDown19.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown19.Location = new System.Drawing.Point(139, 243);
		this.numericUpDown19.Name = "numericUpDown19";
		this.numericUpDown19.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown19.TabIndex = 53;
		this.numericUpDown19.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.domainUpDown13.Items.Add("17.00");
		this.domainUpDown13.Items.Add("17.30");
		this.domainUpDown13.Items.Add("18.00");
		this.domainUpDown13.Items.Add("18.30");
		this.domainUpDown13.Items.Add("19.00");
		this.domainUpDown13.Items.Add("19.30");
		this.domainUpDown13.Items.Add("20.00");
		this.domainUpDown13.Items.Add("20.30");
		this.domainUpDown13.Items.Add("21.00");
		this.domainUpDown13.Items.Add("21.30");
		this.domainUpDown13.Items.Add("22.00");
		this.domainUpDown13.Items.Add("22.30");
		this.domainUpDown13.Location = new System.Drawing.Point(393, 243);
		this.domainUpDown13.Name = "domainUpDown13";
		this.domainUpDown13.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown13.TabIndex = 52;
		this.domainUpDown14.Items.Add("16.00");
		this.domainUpDown14.Items.Add("16.30");
		this.domainUpDown14.Items.Add("17.00");
		this.domainUpDown14.Items.Add("17.30");
		this.domainUpDown14.Items.Add("18.00");
		this.domainUpDown14.Items.Add("18.30");
		this.domainUpDown14.Items.Add("19.00");
		this.domainUpDown14.Items.Add("19.30");
		this.domainUpDown14.Items.Add("20.00");
		this.domainUpDown14.Location = new System.Drawing.Point(309, 243);
		this.domainUpDown14.Name = "domainUpDown14";
		this.domainUpDown14.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown14.TabIndex = 51;
		this.numericUpDown20.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown20.Location = new System.Drawing.Point(55, 243);
		this.numericUpDown20.Name = "numericUpDown20";
		this.numericUpDown20.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown20.TabIndex = 50;
		this.numericUpDown20.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.label15.AutoSize = true;
		this.label15.Location = new System.Drawing.Point(19, 245);
		this.label15.Name = "label15";
		this.label15.Size = new System.Drawing.Size(27, 13);
		this.label15.TabIndex = 49;
		this.label15.Text = "FEB";
		this.numericUpDown21.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown21.Location = new System.Drawing.Point(224, 269);
		this.numericUpDown21.Name = "numericUpDown21";
		this.numericUpDown21.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown21.TabIndex = 60;
		this.numericUpDown21.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericUpDown22.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown22.Location = new System.Drawing.Point(139, 269);
		this.numericUpDown22.Name = "numericUpDown22";
		this.numericUpDown22.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown22.TabIndex = 59;
		this.numericUpDown22.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.domainUpDown15.Items.Add("17.00");
		this.domainUpDown15.Items.Add("17.30");
		this.domainUpDown15.Items.Add("18.00");
		this.domainUpDown15.Items.Add("18.30");
		this.domainUpDown15.Items.Add("19.00");
		this.domainUpDown15.Items.Add("19.30");
		this.domainUpDown15.Items.Add("20.00");
		this.domainUpDown15.Items.Add("20.30");
		this.domainUpDown15.Items.Add("21.00");
		this.domainUpDown15.Items.Add("21.30");
		this.domainUpDown15.Items.Add("22.00");
		this.domainUpDown15.Items.Add("22.30");
		this.domainUpDown15.Location = new System.Drawing.Point(393, 269);
		this.domainUpDown15.Name = "domainUpDown15";
		this.domainUpDown15.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown15.TabIndex = 58;
		this.domainUpDown16.Items.Add("16.00");
		this.domainUpDown16.Items.Add("16.30");
		this.domainUpDown16.Items.Add("17.00");
		this.domainUpDown16.Items.Add("17.30");
		this.domainUpDown16.Items.Add("18.00");
		this.domainUpDown16.Items.Add("18.30");
		this.domainUpDown16.Items.Add("19.00");
		this.domainUpDown16.Items.Add("19.30");
		this.domainUpDown16.Items.Add("20.00");
		this.domainUpDown16.Location = new System.Drawing.Point(309, 269);
		this.domainUpDown16.Name = "domainUpDown16";
		this.domainUpDown16.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown16.TabIndex = 57;
		this.numericUpDown23.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown23.Location = new System.Drawing.Point(55, 269);
		this.numericUpDown23.Name = "numericUpDown23";
		this.numericUpDown23.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown23.TabIndex = 56;
		this.numericUpDown23.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.label16.AutoSize = true;
		this.label16.Location = new System.Drawing.Point(19, 271);
		this.label16.Name = "label16";
		this.label16.Size = new System.Drawing.Size(27, 13);
		this.label16.TabIndex = 55;
		this.label16.Text = "FEB";
		this.numericUpDown24.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown24.Location = new System.Drawing.Point(224, 295);
		this.numericUpDown24.Name = "numericUpDown24";
		this.numericUpDown24.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown24.TabIndex = 66;
		this.numericUpDown24.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericUpDown25.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown25.Location = new System.Drawing.Point(139, 295);
		this.numericUpDown25.Name = "numericUpDown25";
		this.numericUpDown25.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown25.TabIndex = 65;
		this.numericUpDown25.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.domainUpDown17.Items.Add("17.00");
		this.domainUpDown17.Items.Add("17.30");
		this.domainUpDown17.Items.Add("18.00");
		this.domainUpDown17.Items.Add("18.30");
		this.domainUpDown17.Items.Add("19.00");
		this.domainUpDown17.Items.Add("19.30");
		this.domainUpDown17.Items.Add("20.00");
		this.domainUpDown17.Items.Add("20.30");
		this.domainUpDown17.Items.Add("21.00");
		this.domainUpDown17.Items.Add("21.30");
		this.domainUpDown17.Items.Add("22.00");
		this.domainUpDown17.Items.Add("22.30");
		this.domainUpDown17.Location = new System.Drawing.Point(393, 295);
		this.domainUpDown17.Name = "domainUpDown17";
		this.domainUpDown17.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown17.TabIndex = 64;
		this.domainUpDown18.Items.Add("16.00");
		this.domainUpDown18.Items.Add("16.30");
		this.domainUpDown18.Items.Add("17.00");
		this.domainUpDown18.Items.Add("17.30");
		this.domainUpDown18.Items.Add("18.00");
		this.domainUpDown18.Items.Add("18.30");
		this.domainUpDown18.Items.Add("19.00");
		this.domainUpDown18.Items.Add("19.30");
		this.domainUpDown18.Items.Add("20.00");
		this.domainUpDown18.Location = new System.Drawing.Point(309, 295);
		this.domainUpDown18.Name = "domainUpDown18";
		this.domainUpDown18.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown18.TabIndex = 63;
		this.numericUpDown26.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown26.Location = new System.Drawing.Point(55, 295);
		this.numericUpDown26.Name = "numericUpDown26";
		this.numericUpDown26.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown26.TabIndex = 62;
		this.numericUpDown26.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.label17.AutoSize = true;
		this.label17.Location = new System.Drawing.Point(19, 297);
		this.label17.Name = "label17";
		this.label17.Size = new System.Drawing.Size(27, 13);
		this.label17.TabIndex = 61;
		this.label17.Text = "FEB";
		this.numericUpDown27.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown27.Location = new System.Drawing.Point(224, 321);
		this.numericUpDown27.Name = "numericUpDown27";
		this.numericUpDown27.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown27.TabIndex = 72;
		this.numericUpDown27.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericUpDown28.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown28.Location = new System.Drawing.Point(139, 321);
		this.numericUpDown28.Name = "numericUpDown28";
		this.numericUpDown28.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown28.TabIndex = 71;
		this.numericUpDown28.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.domainUpDown19.Items.Add("17.00");
		this.domainUpDown19.Items.Add("17.30");
		this.domainUpDown19.Items.Add("18.00");
		this.domainUpDown19.Items.Add("18.30");
		this.domainUpDown19.Items.Add("19.00");
		this.domainUpDown19.Items.Add("19.30");
		this.domainUpDown19.Items.Add("20.00");
		this.domainUpDown19.Items.Add("20.30");
		this.domainUpDown19.Items.Add("21.00");
		this.domainUpDown19.Items.Add("21.30");
		this.domainUpDown19.Items.Add("22.00");
		this.domainUpDown19.Items.Add("22.30");
		this.domainUpDown19.Location = new System.Drawing.Point(393, 321);
		this.domainUpDown19.Name = "domainUpDown19";
		this.domainUpDown19.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown19.TabIndex = 70;
		this.domainUpDown20.Items.Add("16.00");
		this.domainUpDown20.Items.Add("16.30");
		this.domainUpDown20.Items.Add("17.00");
		this.domainUpDown20.Items.Add("17.30");
		this.domainUpDown20.Items.Add("18.00");
		this.domainUpDown20.Items.Add("18.30");
		this.domainUpDown20.Items.Add("19.00");
		this.domainUpDown20.Items.Add("19.30");
		this.domainUpDown20.Items.Add("20.00");
		this.domainUpDown20.Location = new System.Drawing.Point(309, 321);
		this.domainUpDown20.Name = "domainUpDown20";
		this.domainUpDown20.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown20.TabIndex = 69;
		this.numericUpDown29.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown29.Location = new System.Drawing.Point(55, 321);
		this.numericUpDown29.Name = "numericUpDown29";
		this.numericUpDown29.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown29.TabIndex = 68;
		this.numericUpDown29.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.label18.AutoSize = true;
		this.label18.Location = new System.Drawing.Point(19, 323);
		this.label18.Name = "label18";
		this.label18.Size = new System.Drawing.Size(27, 13);
		this.label18.TabIndex = 67;
		this.label18.Text = "FEB";
		this.numericUpDown30.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown30.Location = new System.Drawing.Point(224, 347);
		this.numericUpDown30.Name = "numericUpDown30";
		this.numericUpDown30.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown30.TabIndex = 78;
		this.numericUpDown30.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.numericUpDown31.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown31.Location = new System.Drawing.Point(139, 347);
		this.numericUpDown31.Name = "numericUpDown31";
		this.numericUpDown31.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown31.TabIndex = 77;
		this.numericUpDown31.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.domainUpDown21.Items.Add("17.00");
		this.domainUpDown21.Items.Add("17.30");
		this.domainUpDown21.Items.Add("18.00");
		this.domainUpDown21.Items.Add("18.30");
		this.domainUpDown21.Items.Add("19.00");
		this.domainUpDown21.Items.Add("19.30");
		this.domainUpDown21.Items.Add("20.00");
		this.domainUpDown21.Items.Add("20.30");
		this.domainUpDown21.Items.Add("21.00");
		this.domainUpDown21.Items.Add("21.30");
		this.domainUpDown21.Items.Add("22.00");
		this.domainUpDown21.Items.Add("22.30");
		this.domainUpDown21.Location = new System.Drawing.Point(393, 347);
		this.domainUpDown21.Name = "domainUpDown21";
		this.domainUpDown21.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown21.TabIndex = 76;
		this.domainUpDown22.Items.Add("16.00");
		this.domainUpDown22.Items.Add("16.30");
		this.domainUpDown22.Items.Add("17.00");
		this.domainUpDown22.Items.Add("17.30");
		this.domainUpDown22.Items.Add("18.00");
		this.domainUpDown22.Items.Add("18.30");
		this.domainUpDown22.Items.Add("19.00");
		this.domainUpDown22.Items.Add("19.30");
		this.domainUpDown22.Items.Add("20.00");
		this.domainUpDown22.Location = new System.Drawing.Point(309, 347);
		this.domainUpDown22.Name = "domainUpDown22";
		this.domainUpDown22.Size = new System.Drawing.Size(79, 20);
		this.domainUpDown22.TabIndex = 75;
		this.numericUpDown32.Increment = new decimal(new int[4] { 10, 0, 0, 0 });
		this.numericUpDown32.Location = new System.Drawing.Point(55, 347);
		this.numericUpDown32.Name = "numericUpDown32";
		this.numericUpDown32.Size = new System.Drawing.Size(79, 20);
		this.numericUpDown32.TabIndex = 74;
		this.numericUpDown32.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
		this.label19.AutoSize = true;
		this.label19.Location = new System.Drawing.Point(19, 349);
		this.label19.Name = "label19";
		this.label19.Size = new System.Drawing.Size(27, 13);
		this.label19.TabIndex = 73;
		this.label19.Text = "FEB";
		this.buttonOk.DialogResult = System.Windows.Forms.DialogResult.OK;
		this.buttonOk.Location = new System.Drawing.Point(140, 377);
		this.buttonOk.Name = "buttonOk";
		this.buttonOk.Size = new System.Drawing.Size(75, 23);
		this.buttonOk.TabIndex = 79;
		this.buttonOk.Text = "OK";
		this.buttonOk.UseVisualStyleBackColor = true;
		this.buttonCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
		this.buttonCancel.Location = new System.Drawing.Point(284, 377);
		this.buttonCancel.Name = "buttonCancel";
		this.buttonCancel.Size = new System.Drawing.Size(75, 23);
		this.buttonCancel.TabIndex = 80;
		this.buttonCancel.Text = "Cancel";
		this.buttonCancel.UseVisualStyleBackColor = true;
		base.AutoScaleDimensions = new System.Drawing.SizeF(6f, 13f);
		base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
		base.ClientSize = new System.Drawing.Size(481, 408);
		base.Controls.Add(this.buttonCancel);
		base.Controls.Add(this.buttonOk);
		base.Controls.Add(this.numericUpDown30);
		base.Controls.Add(this.numericUpDown31);
		base.Controls.Add(this.domainUpDown21);
		base.Controls.Add(this.domainUpDown22);
		base.Controls.Add(this.numericUpDown32);
		base.Controls.Add(this.label19);
		base.Controls.Add(this.numericUpDown27);
		base.Controls.Add(this.numericUpDown28);
		base.Controls.Add(this.domainUpDown19);
		base.Controls.Add(this.domainUpDown20);
		base.Controls.Add(this.numericUpDown29);
		base.Controls.Add(this.label18);
		base.Controls.Add(this.numericUpDown24);
		base.Controls.Add(this.numericUpDown25);
		base.Controls.Add(this.domainUpDown17);
		base.Controls.Add(this.domainUpDown18);
		base.Controls.Add(this.numericUpDown26);
		base.Controls.Add(this.label17);
		base.Controls.Add(this.numericUpDown21);
		base.Controls.Add(this.numericUpDown22);
		base.Controls.Add(this.domainUpDown15);
		base.Controls.Add(this.domainUpDown16);
		base.Controls.Add(this.numericUpDown23);
		base.Controls.Add(this.label16);
		base.Controls.Add(this.numericUpDown18);
		base.Controls.Add(this.numericUpDown19);
		base.Controls.Add(this.domainUpDown13);
		base.Controls.Add(this.domainUpDown14);
		base.Controls.Add(this.numericUpDown20);
		base.Controls.Add(this.label15);
		base.Controls.Add(this.numericUpDown15);
		base.Controls.Add(this.numericUpDown16);
		base.Controls.Add(this.domainUpDown11);
		base.Controls.Add(this.domainUpDown12);
		base.Controls.Add(this.numericUpDown17);
		base.Controls.Add(this.label14);
		base.Controls.Add(this.numericUpDown12);
		base.Controls.Add(this.numericUpDown13);
		base.Controls.Add(this.domainUpDown9);
		base.Controls.Add(this.domainUpDown10);
		base.Controls.Add(this.numericUpDown14);
		base.Controls.Add(this.label13);
		base.Controls.Add(this.numericUpDown9);
		base.Controls.Add(this.numericUpDown10);
		base.Controls.Add(this.domainUpDown7);
		base.Controls.Add(this.domainUpDown8);
		base.Controls.Add(this.numericUpDown11);
		base.Controls.Add(this.label12);
		base.Controls.Add(this.numericUpDown6);
		base.Controls.Add(this.numericUpDown7);
		base.Controls.Add(this.domainUpDown5);
		base.Controls.Add(this.domainUpDown6);
		base.Controls.Add(this.numericUpDown8);
		base.Controls.Add(this.label11);
		base.Controls.Add(this.numericUpDown3);
		base.Controls.Add(this.numericUpDown4);
		base.Controls.Add(this.domainUpDown3);
		base.Controls.Add(this.domainUpDown4);
		base.Controls.Add(this.numericUpDown5);
		base.Controls.Add(this.label10);
		base.Controls.Add(this.numericUpDown1);
		base.Controls.Add(this.numericUpDown2);
		base.Controls.Add(this.domainUpDown1);
		base.Controls.Add(this.domainUpDown2);
		base.Controls.Add(this.numericFebOvercast);
		base.Controls.Add(this.label9);
		base.Controls.Add(this.numericJanSnow);
		base.Controls.Add(this.numericJanRain);
		base.Controls.Add(this.domainJanDark);
		base.Controls.Add(this.domainJanSunset);
		base.Controls.Add(this.numericJanOvercast);
		base.Controls.Add(this.label7);
		base.Controls.Add(this.label8);
		base.Controls.Add(this.label6);
		base.Controls.Add(this.label5);
		base.Controls.Add(this.label4);
		base.Controls.Add(this.label3);
		base.Controls.Add(this.label2);
		base.Controls.Add(this.label1);
		base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Fixed3D;
		base.Icon = (System.Drawing.Icon)resources.GetObject("$this.Icon");
		base.Name = "WeatherForm";
		this.Text = "Weather";
		((System.ComponentModel.ISupportInitialize)this.numericJanOvercast).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericJanRain).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericJanSnow).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown1).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown2).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericFebOvercast).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown3).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown4).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown5).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown6).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown7).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown8).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown9).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown10).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown11).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown12).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown13).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown14).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown15).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown16).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown17).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown18).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown19).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown20).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown21).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown22).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown23).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown24).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown25).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown26).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown27).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown28).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown29).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown30).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown31).EndInit();
		((System.ComponentModel.ISupportInitialize)this.numericUpDown32).EndInit();
		base.ResumeLayout(false);
		base.PerformLayout();
	}
}
