<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CM26 Mod Manager</AssemblyName>
    <RootNamespace>CM26.ModManager</RootNamespace>
    <ApplicationIcon>..\CM26.App\Assets\Logo\Creation Master 26.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="..\CM26.App\CM26.App.csproj" /></ItemGroup>
</Project>
