<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>FifaLibrary16</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="9.0.0" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Numerics" />
    <Reference Include="zlib.net">
      <HintPath>..\CM26.LegacyUI\vendor\zlib.net.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
