<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>FifaControls</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
    <PackageReference Include="System.Resources.Extensions" Version="9.0.0" />
    <ProjectReference Include="..\CM26.Legacy.FifaLibrary\CM26.Legacy.FifaLibrary.csproj" />
    <Reference Include="System.Data" />
    <Reference Include="Microsoft.DirectX">
      <HintPath>..\CM26.LegacyUI\vendor\Microsoft.DirectX.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.DirectX.Direct3D">
      <HintPath>..\CM26.LegacyUI\vendor\Microsoft.DirectX.Direct3D.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.DirectX.Direct3DX">
      <HintPath>..\CM26.LegacyUI\vendor\Microsoft.DirectX.Direct3DX.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
